%E.E.E.-analyzer - Gui_main by Fabio Pinciroli
%Copyright 2017 Fabio Pinciroli DISTRIBUTED UNDER GPL V3 LICENSE

% Start initialization code - DO NOT EDIT - AUTOGENERATED
function varargout = Gui_main(varargin)
    gui_Singleton = 1;
    gui_State = struct('gui_Name',       mfilename, ...
                       'gui_Singleton',  gui_Singleton, ...
                       'gui_OpeningFcn', @Gui_main_OpeningFcn, ...
                       'gui_OutputFcn',  @Gui_main_OutputFcn, ...
                       'gui_LayoutFcn',  [] , ...
                       'gui_Callback',   []);
    if nargin && ischar(varargin{1})
        gui_State.gui_Callback = str2func(varargin{1});
    end

    if nargout
        [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
    else
        gui_mainfcn(gui_State, varargin{:});
    end
end
function varargout = Gui_main_OutputFcn(hObject, eventdata, handles) 
    varargout{1} = handles.output;
end
function txt_Filepath_CreateFcn(hObject, eventdata, handles)

    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end
% End initialization code - DO NOT EDIT - AUTOGENERATED

%CALLBACKS-----------------------------------------------------------------
% Initialization callback(executes when window is shown)
function Gui_main_OpeningFcn(hObject, eventdata, handles, varargin)
    handles.output = hObject;   %autogenerated
    guidata(hObject, handles);  %autogenerated
end


% --- Executes on button press in btn_Go.
function btn_Go_Callback(hObject, eventdata, handles)
end


% --- Executes on button press in btn_ChooseFile.
function btn_ChooseFile_Callback(hObject, eventdata, handles)
end




function txt_Filepath_Callback(hObject, eventdata, handles)
end


